# NaVILA Client Parameters (Step-by-step navigation mode)
navila_core:
  ros__parameters:
    server_url: "http://10.16.117.238:8000"
    num_frames: 8
    instruction: "navigate to the goal"
    jpeg_quality: 80

    # Motion control parameters
    forward_speed_ratio: 0.3
    turn_speed_ratio: 0.9
    forward_speed_ms: 0.2
    turn_speed_degs: 36.0
    stop_duration: 0.01
    stabilize_duration: 0.01
